const ALL_GENRES = { id: "", name: "All Genres" };

const GENRES = [
  ALL_GENRES,
  { id: "95", name: "140 / Deep Dubstep / Grime" },
  { id: "102", name: "African" },
  { id: "89", name: "Afro House" },
  { id: "98", name: "Amapiano" },
  { id: "100", name: "Ambient / Experimental" },
  { id: "85", name: "Bass / Club" },
  { id: "91", name: "Bass House" },
  { id: "79", name: "Big Room" },
  { id: "101", name: "Brazilian Funk" },
  { id: "9", name: "Breaks / Breakbeat / UK Bass" },
  { id: "103", name: "Caribbean" },
  { id: "104", name: "Country" },
  { id: "39", name: "Dance / Pop" },
  { id: "12", name: "Deep House" },
  { id: "16", name: "DJ Tools" },
  { id: "63", name: "Downtempo" },
  { id: "1", name: "Drum & Bass" },
  { id: "18", name: "Dubstep" },
  { id: "94", name: "Electro (Classic / Detroit / Modern)" },
  { id: "17", name: "Electro House" },
  { id: "3", name: "Electronica" },
  { id: "40", name: "Funk / Soul / Disco" },
  { id: "81", name: "Funky House" },
  { id: "65", name: "Future House" },
  { id: "49", name: "Glitch Hop" },
  { id: "8", name: "Hard Dance / Hardcore" },
  { id: "2", name: "Hard Techno" },
  { id: "105", name: "Hip-Hop" },
  { id: "5", name: "House" },
  { id: "37", name: "Indie Dance" },
  { id: "97", name: "Jackin House" },
  { id: "106", name: "Latin" },
  { id: "111", name: "Latin Electronic" },
  { id: "80", name: "Leftfield House & Techno" },
  { id: "90", name: "Melodic House & Techno" },
  { id: "14", name: "Minimal / Deep Tech" },
  { id: "50", name: "Nu Disco / Disco" },
  { id: "93", name: "Organic House" },
  { id: "107", name: "Pop" },
  { id: "15", name: "Progressive House" },
  { id: "13", name: "Psy-Trance" },
  { id: "108", name: "R&B" },
  { id: "41", name: "Reggae / Dancehall / Dub" },
  { id: "109", name: "Rock" },
  { id: "11", name: "Tech House" },
  { id: "6", name: "Techno (Peak Time / Driving)" },
  { id: "92", name: "Techno (Raw / Deep / Hypnotic)" },
  { id: "7", name: "Trance" },
  { id: "99", name: "Trance (Raw / Deep / Hypnotic)" },
  { id: "87", name: "Trap / Future Bass" },
  { id: "38", name: "Trap / Wave" },
  { id: "86", name: "UK Garage / Bassline" }
];
